version: '3.8'

services:
  dagster:
    build:
      context: ./services/dagster
    container_name: dagster
    ports:
      - "3000:3000"
    networks:
      - prj_network
    volumes:
      - ./services/dagster/src:/app
    environment:
      DAGSTER_RUN_STORAGE_CONFIG_CONNECTION_URI: postgresql://dagster:dagster@postgres:5432/dagster
    depends_on:
      - postgres
  postgres:
    image: postgres:13.3
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    networks:
      - prj_network
    volumes:
      - ./data_store/postgres_data:/var/lib/postgresql/data
    user: "501"

networks:
  prj_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
